# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o hava-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -v -o hava-darwin-amd64 .
          GOOS=windows GOARCH=amd64 go build -v -o hava-windows-amd64.exe .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hava-binaries
          path: |
            hava-linux-amd64
            hava-darwin-amd64
            hava-windows-amd64.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: hava-binaries

      - name: Set up GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            hava-linux-amd64
            hava-darwin-amd64
            hava-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
